# Generated by Django 5.2.4 on 2025-07-03 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bascula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaDeEntrada',
            fields=[
                ('folio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('placas_camion', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('FINALIZADA', 'Finalizada')], default='PENDIENTE', max_length=10)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bascula.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='LineaDeNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilos', models.IntegerField()),
                ('linea_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rebajes', to='bascula.lineadenota')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bascula.material')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='bascula.notadeentrada')),
            ],
        ),
    ]
